In [2]:
!pip install cutecharts

In [11]:
import pandas as pd
import cutecharts.charts as ctc

AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import)

In [7]:
microdados_enem_rj = pd.read_csv('../Data/microdados_enem_ufs_2019/microdados_enem_RJ_2019.csv', index_col=0)

NameError: name 'pd' is not defined

In [23]:
microdados_enem_rj.head()

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
10600,190001015227,2019,3302056,Italva,33,RJ,32,F,1,3,...,A,A,A,B,B,A,B,A,A,A
21074,190001025702,2019,3305109,São João de Meriti,33,RJ,32,M,1,3,...,A,A,A,B,A,A,B,A,A,A
22657,190001027285,2019,3304557,Rio de Janeiro,33,RJ,26,M,1,3,...,B,A,A,B,A,A,B,A,B,B
30365,190001034993,2019,3304557,Rio de Janeiro,33,RJ,19,F,1,3,...,A,A,A,A,A,A,B,A,A,B
60937,190001065566,2019,3304557,Rio de Janeiro,33,RJ,22,F,1,3,...,A,A,A,B,B,A,C,A,A,A

In [24]:
microdados_enem_rj.reset_index(inplace=True,drop=True)

In [25]:
microdados_enem_rj

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001015227,2019,3302056,Italva,33,RJ,32,F,1,3,...,A,A,A,B,B,A,B,A,A,A
1,190001025702,2019,3305109,São João de Meriti,33,RJ,32,M,1,3,...,A,A,A,B,A,A,B,A,A,A
2,190001027285,2019,3304557,Rio de Janeiro,33,RJ,26,M,1,3,...,B,A,A,B,A,A,B,A,B,B
3,190001034993,2019,3304557,Rio de Janeiro,33,RJ,19,F,1,3,...,A,A,A,A,A,A,B,A,A,B
4,190001065566,2019,3304557,Rio de Janeiro,33,RJ,22,F,1,3,...,A,A,A,B,B,A,C,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338705,190006118895,2019,3304557,Rio de Janeiro,33,RJ,18,F,0,3,...,B,A,B,D,A,B,E,B,A,B
338706,190006118896,2019,3305109,São João de Meriti,33,RJ,52,F,2,3,...,A,A,A,B,A,A,B,B,A,A
338707,190006118897,2019,3304557,Rio de Janeiro,33,RJ,23,F,1,1,...,B,A,A,D,B,B,E,A,B,B
338708,190006118898,2019,3300308,Barra do Piraí,33,RJ,32,F,1,2,...,A,A,A,B,B,A,B,A,A,A
338709,190006118899,2019,3304904,São Gonçalo,33,RJ,41,F,0,3,...,B,A,A,B,A,A,C,A,B,B

In [27]:
microdados_enem_rj.SG_UF_RESIDENCIA.unique()

array(['RJ'], dtype=object)

In [28]:
microdados_enem_rj.columns.values

array(['NU_INSCRICAO', 'NU_ANO', 'CO_MUNICIPIO_RESIDENCIA',
       'NO_MUNICIPIO_RESIDENCIA', 'CO_UF_RESIDENCIA', 'SG_UF_RESIDENCIA',
       'NU_IDADE', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA',
       'TP_NACIONALIDADE', 'CO_MUNICIPIO_NASCIMENTO',
       'NO_MUNICIPIO_NASCIMENTO', 'CO_UF_NASCIMENTO', 'SG_UF_NASCIMENTO',
       'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO',
       'IN_TREINEIRO', 'CO_ESCOLA', 'CO_MUNICIPIO_ESC',
       'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC',
       'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC',
       'IN_BAIXA_VISAO', 'IN_CEGUEIRA', 'IN_SURDEZ',
       'IN_DEFICIENCIA_AUDITIVA', 'IN_SURDO_CEGUEIRA',
       'IN_DEFICIENCIA_FISICA', 'IN_DEFICIENCIA_MENTAL',
       'IN_DEFICIT_ATENCAO', 'IN_DISLEXIA', 'IN_DISCALCULIA',
       'IN_AUTISMO', 'IN_VISAO_MONOCULAR', 'IN_OUTRA_DEF', 'IN_GESTANTE',
       'IN_LACTANTE', 'IN_IDOSO', 'IN_ESTUDA_CLASSE_HOSPITALAR',
       'IN_SEM_RECURSO', 'IN_BRAILLE', 'IN_AMPLIADA_24', 'IN_AMPLIADA_18',
       'IN_LEDOR', 'IN_ACESSO', 'IN_TRANSCRICAO', 'IN_LIBRAS',
       'IN_TEMPO_ADICIONAL', 'IN_LEITURA_LABIAL', 'IN_MESA_CADEIRA_RODAS',
       'IN_MESA_CADEIRA_SEPARADA', 'IN_APOIO_PERNA', 'IN_GUIA_INTERPRETE',
       'IN_COMPUTADOR', 'IN_CADEIRA_ESPECIAL', 'IN_CADEIRA_CANHOTO',
       'IN_CADEIRA_ACOLCHOADA', 'IN_PROVA_DEITADO', 'IN_MOBILIARIO_OBESO',
       'IN_LAMINA_OVERLAY', 'IN_PROTETOR_AURICULAR', 'IN_MEDIDOR_GLICOSE',
       'IN_MAQUINA_BRAILE', 'IN_SOROBAN', 'IN_MARCA_PASSO', 'IN_SONDA',
       'IN_MEDICAMENTOS', 'IN_SALA_INDIVIDUAL', 'IN_SALA_ESPECIAL',
       'IN_SALA_ACOMPANHANTE', 'IN_MOBILIARIO_ESPECIFICO',
       'IN_MATERIAL_ESPECIFICO', 'IN_NOME_SOCIAL', 'CO_MUNICIPIO_PROVA',
       'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA',
       'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC',
       'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH',
       'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'TP_LINGUA',
       'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC',
       'TX_GABARITO_MT', 'TP_STATUS_REDACAO', 'NU_NOTA_COMP1',
       'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4', 'NU_NOTA_COMP5',
       'NU_NOTA_REDACAO', 'Q001', 'Q002', 'Q003', 'Q004', 'Q005', 'Q006',
       'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014',
       'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022',
       'Q023', 'Q024', 'Q025'], dtype=object)

In [30]:
microdados_enem_rj[['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT']].mean()

NU_NOTA_CN    491.892385
NU_NOTA_CH    523.361916
NU_NOTA_LC    535.900530
NU_NOTA_MT    539.564877
dtype: float64

In [63]:
chart = ctc.Bar('Médias Notas RJ',width='500px',height='400px')
chart.set_options(
 labels=['C. Natureza', 'C. Humanas', 'Linguagens', 'Matemática', 'Redação'],
 x_label="Provas",
 y_label="Média por Prova" ,
 colors=['#D9F1BB','#F7B7A3','#EA5F89','#9B3192', '#FFFF77']
 )
chart.add_series("Média",list(microdados_enem_rj[['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT', 'NU_NOTA_REDACAO']].mean()))
chart.render_notebook()

In [68]:
municipio = "Angra dos Reis"

radar_chart = ctc.Radar('Médias Notas RJ',width='600px',height='600px')
radar_chart.set_options(
 labels=['C. Natureza', 'C. Humanas', 'Linguagens', 'Matemática'],
 is_show_legend=True, #by default, it is true. You can turn it off.
 legend_pos='upRight'  #location of the legend
 )

radar_chart.add_series("Média dos Municípios RJ",list(microdados_enem_rj[['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT','NU_NOTA_REDACAO']].mean()))
radar_chart.add_series("Média do Município {}".format(municipio),
                       list(microdados_enem_rj.groupby(['NO_MUNICIPIO_RESIDENCIA'])['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT','NU_NOTA_REDACAO'].mean().loc[municipio]))

radar_chart.render_notebook()

In [51]:
microdados_enem_rj.groupby(['NO_MUNICIPIO_RESIDENCIA'])['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT'].mean().loc['Angra dos Reis']

NU_NOTA_CN    475.984038
NU_NOTA_CH    508.694181
NU_NOTA_LC    527.015926
NU_NOTA_MT    520.845753
Name: Angra dos Reis, dtype: float64

In [52]:
microdados_enem_rj.groupby(['NO_MUNICIPIO_RESIDENCIA'])['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC',
       'NU_NOTA_MT'].mean()

                         NU_NOTA_CN  NU_NOTA_CH  NU_NOTA_LC  NU_NOTA_MT
NO_MUNICIPIO_RESIDENCIA
Angra dos Reis           475.984038  508.694181  527.015926  520.845753
Aperibé                  493.393789  518.341379  528.701724  542.992547
Araruama                 488.075321  514.994308  529.860574  532.785762
Areal                    474.303145  503.188304  523.457895  515.313208
Armação dos Búzios       490.474903  525.274910  535.007040  530.700000
...                             ...         ...         ...         ...
Três Rios                482.053123  511.984375  527.105288  522.841703
Valença                  495.254925  522.922297  534.024662  546.180657
Varre-Sai                492.420492  503.276692  512.384211  534.113934
Vassouras                485.166593  513.554167  528.432917  525.596239
Volta Redonda            507.400156  535.504062  544.084667  569.327552

[92 rows x 4 columns]